### ISSUE TITLE
DontAskJustExecute also on page exit is annoying :)

### ISSUE THREAD

**Issue by TopSwagCode** [ctrl-alt-d/BlazorConfirm#1]
Hi. Playing around with Blazor and found this.
Think it's a cool little package.

The prototype I am building for fun right now, I want to popup with "Are you sure you want to delete item X".
It works fine. But after I delete an item and want to close browser I get confirm box again.

I have made a quickfix:

        blazorConfirmDialog.DontAskjJustExecute = false;    

        blazorConfirmDialog.NewDialog(message: "Are you sure that you want to remove this forecast?",
                               onSuccessDelegate: (() =>
                               {
                                   deleteX();
                                   StateHasChanged();
                               }));

        blazorConfirmDialog.DontAskjJustExecute = true;

It's nothing important.  :) Keep up the good work.

**Comment by ctrl-alt-d** [comment]
Hi @kiksen1987,

first of all, thanks about your feedback. About the issue:

>"this is not a bug, it's a feature".

The main goal of library is to avoid lost changes. You can turn off `confirm` at any moment. When you turn of `confirm` with `blazorConfirmDialog.DontAskjJustExecute`, all dialog is turned off, including onunloadwindow dialog.

May be something like this runs for you:

```c#
    blazorConfirmDialog.DontAskjJustExecute = false;    

    blazorConfirmDialog.NewDialog(message: "Are you sure that ... forecast?",
                           onSuccessDelegate: (() =>
                           {
                               deleteX();
                               blazorConfirmDialog.DontAskjJustExecute = true; // <-- here
                               StateHasChanged();
                           }));
```
Let me know if this solves your issue.

Regards.

**Comment by IvanJosipovic** [comment]
I agree with @kiksen1987, I don't think confirm on exit should be on by default. I just want a simple dialog, the confirm on exit should be enabled manually.

I think repeating the code mentioned above is not very clean. We shouldn't have to toggle DontAskjJustExecute for every dialog.

**Comment by ctrl-alt-d** [comment]
Hi @IvanJosipovic and @kiksen1987. I will think about it. Thanks a lot about the feedback.

At this time my idea was to don't lost data in few moments (while editing). I post here gif to illustrate it:


![dont lost changes](https://user-images.githubusercontent.com/3105983/52643024-6db87a00-2edc-11e9-98a7-bcbd8d4cfd60.gif)

( in picture, the green button "desa", means "save" )

Any case, I will think about your suggestion!
